name: $(Rev:rrrrr)
pool:
  name: CSG OnPrem VS2019
trigger:
- master
- rel/*
steps:
- task: PowerShell@1
  displayName: 'Build + Test'
  inputs:
    scriptName: build.ps1
    arguments: '-BuildNumber $(Build.BuildNumber) -NoTest'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: 'tests\**\*Test.csproj'
    arguments: '--no-build --configuration Release'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts-classlib'
  inputs:
    PathtoPublish: src/Csg.AspNetCore.ExceptionManagement/bin/Release
    ArtifactName: classlib
